name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup
      run: brew install boost capnp google-sparsehash multimarkdown ninja ragel
    - name: Configure
      run: ./configure
    - name: Build
      run: ninja TextMate
